### ISSUE TITLE
Styling of select2 vs. regular select

### ISSUE THREAD

**Issue by mbaas2** [angel-vladov/select2-bootstrap-theme#5]
I'm struggling to get proper layout for the select2-Controls in Bootstrap4.
Here's a [fiddle](https://jsfiddle.net/mbaas/sr2omuqn/) with comments about the issues. 
I'm not sure if this is a real "bug" of if I am not using it correctly - would appreciate some help!

**Comment by angel-vladov** [comment]
I guess you've probably figured it by now, but you must add `containerCssClass: ':all:'` and use select2 full for the theme to work properly.

Check [here](https://github.com/select2/select2-bootstrap-theme/pull/72#issuecomment-399660488)
